services:
  appshell:
    profiles:
      - host
    # image: appshell/react-host:latest # production image (no hot module replacement support)
    image: appshell/react-host:developer
    env_file: ./${ENV_TARGET}.env
    command: ${APPSHELL_CONTAINER_COMMAND}
    deploy:
      mode: replicated
      replicas: ${APPSHELL_CONTAINER_SCALE}
    ports:
      - ${APPSHELL_PORT}:${APPSHELL_PORT}
    volumes:
      - ./${ENV_TARGET}.env/:/appshell/${ENV_TARGET}.env
      - ./appshell_registry:/appshell/appshell_registry

  appshell-sample-mfe-apps:
    profiles:
      - apps
    env_file: ./${ENV_TARGET}.env
    command: ${CONTAINER_COMMAND}
    build:
      context: .
      target: ${BUILD_TARGET}
    deploy:
      mode: replicated
      replicas: ${CONTAINER_SCALE}
    ports:
      - ${SAMPLE_MFE_CONTAINER_PORT}:${SAMPLE_MFE_CONTAINER_PORT}
      - ${SAMPLE_MFE_PING_PORT}:${SAMPLE_MFE_PING_PORT}
      - ${SAMPLE_MFE_PONG_PORT}:${SAMPLE_MFE_PONG_PORT}
    volumes:
      - ./apps:/appshell/apps
      - ./${ENV_TARGET}.env/:/appshell/${ENV_TARGET}.env
      - ./appshell_registry:/appshell/appshell_registry
